# Generated by Django 4.2.17 on 2024-12-26 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airdrops',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('link', models.URLField()),
                ('cost', models.FloatField()),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing Airdrops'), ('upcoming', 'Upcoming Airdrops'), ('ended', 'Ended Airdrops')], default='ongoing', max_length=20)),
                ('reward_date', models.DateField()),
                ('airdrop_confidentiality', models.CharField(choices=[('confirmed', 'Confirmed'), ('not-confirmed', 'Not Confirmed')], default='confirmed', max_length=20)),
                ('fund_raised', models.FloatField()),
                ('backers', models.CharField(max_length=255)),
                ('website', models.URLField()),
                ('social_medias', models.JSONField()),
                ('eligibility_checker', models.URLField()),
                ('claim_airdrop', models.URLField()),
                ('image', models.ImageField(upload_to='airdrops/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='steps/')),
                ('airdrop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='mcapp.airdrops')),
            ],
        ),
    ]
